//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Module
{
	private Memory mem
	{
		get;
		set;
	}

	private vector<Socket> sockets
	{
		get;
		set;
	}

	private string name
	{
		get;
		set;
	}

	private vector<Message> messages
	{
		get;
		set;
	}

	public virtual Socket Socket
	{
		get;
		set;
	}

	public virtual int input(object adress, object data, object Command)
	{
		throw new System.NotImplementedException();
	}

	public virtual int output(object adress, object data, object Command)
	{
		throw new System.NotImplementedException();
	}

	protected abstract int process(object ?);

}

